### ISSUE TITLE
Switches image

### ISSUE THREAD

**Issue by akileos** [dereulenspiegel/HABSweetie#4]
Upon first load of sitemap, switches with image "light" do not display correct image but "ak quin et".

Works correctly when sending On & Off commands.
Impacted items : 
Switch Light_RS_Bureau "Bureau"  (Lights,L_Anx) { knx="<4/1/0" }

**Comment by akileos** [comment]
Screencap here : https://dl.dropboxusercontent.com/u/2370267/scrot/hab.png

**Comment by dereulenspiegel** [comment]
Is this issue still a problem? I couldn't reproduce this behaviour and I hope that fixing the encoding problems also fixed this issue.

**Comment by akileos** [comment]
Looks good now. Thanks
